# Generated by Django 2.0.4 on 2018-04-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foss.user')),
            ],
        ),
        migrations.CreateModel(
            name='tutorial_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=1000)),
                ('expected_submission_date', models.DateField()),
                ('actual_submission_date', models.DateField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foss.user')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foss.foss')),
            ],
        ),
    ]
