# Generated by Django 2.0.4 on 2018-04-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foss', '0002_foss_payment_tutorial_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial_detail',
            old_name='actual_submission_date',
            new_name='act_sub_date',
        ),
        migrations.RenameField(
            model_name='tutorial_detail',
            old_name='expected_submission_date',
            new_name='exp_sub_date',
        ),
        migrations.RenameField(
            model_name='tutorial_detail',
            old_name='contributor',
            new_name='publisher',
        ),
    ]
