# Generated by Django 2.0.4 on 2018-04-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foss', '0003_auto_20180404_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='contributor',
            new_name='publisher',
        ),
    ]
