# Generated by Django 2.0.4 on 2018-04-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foss', '0004_auto_20180404_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
